### ISSUE TITLE
Allow optional prefix

### ISSUE THREAD

**Issue by jayphelps** [jonathantneal/postcss-short#1]
To prevent clashes with future syntax it would be rad if we could define (with a default) a prefix.

``` css
foo {
  -postcss-size: 10px;
}
```
