### ISSUE TITLE
Removes !important flag

### ISSUE THREAD

**Issue by gavinmcfarland** [jonathantneal/postcss-short#22]
Hi, I noticed this by accident, but *postcss-short* I believe is not accounting for the CSS `!important` flag.

I noticed this with `font-size`.

For example:

```css
p {
  font-size: inherit !important;
}
```

Results in:

```css
p {
  font-size: inherit;
```

I'm not sure if other properties have the same issue, I can check when I get a chance.
