### ISSUE TITLE
"*" properties do not work

### ISSUE THREAD

**Issue by azat-io** [jonathantneal/postcss-short#5]
When I write something like this:

``` css
div {
  margin: * auto;
}
```

Nothing happens. Everything else works fine.
